name: Building GSI..

on:
  watch:
    types: [started]
    
env:
  ROM_URL:  https://s262.turbobit.net/download.php?name=TUR-A505FDDS5BTG3-20200727190000.zip&md5=1be8720a56d419193c860b0377cfa877&fid=8bt4zazqcmhj&uid=free&speed=59&till=1607612889&trycount=1&ip=188.57.169.9&sid=3ffee33ac613bcac4928dda1b0ed3e85&browser=c3802dabd7e2962072930d457c5b12ce&did=2414820323&secure=1&sign=2a2711d76df6b2d6060eaae8ad734133
  ROM_NAME: OneUI
  TZ: Asia/Kolkata
  MIR: wet
  ZIP_NAME: Flyme-8
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules  https://github.com/doganoo65/ErfanGSIs-VelanGSIs.git  ErfanGSİs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z          
       - name: Zip AB and upload 
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
